name: Deploy Media Theme to DotNest

on:
  push:
    branches:
      - demo-dev
    paths:
      - 'src/Themes/DotNest.MediaThemeDemo.Theme/**'

jobs:
  deploy-media-theme:
    uses: Lombiq/Hosting-Media-Theme/.github/workflows/deploy-media-theme.yml@dev
    secrets:
      URL: ${{ secrets.MEDIA_THEME_DEMO_DEPLOYMENT_URL }}
      CLIENT_NAME: ${{ secrets.MEDIA_THEME_DEMO_DEPLOYMENT_CLIENT_NAME }}
      CLIENT_API_KEY: ${{ secrets.MEDIA_THEME_DEMO_DEPLOYMENT_CLIENT_API_KEY }}
    with:
      theme-path: "src/Themes/DotNest.MediaThemeDemo.Theme"
